language: node_js

node_js:
  - stable

install:
  - yarn install

notifications:
  email: false

cache:
  directories:
    - node_modules

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
on:
  branch: master
