name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yarn run build
        
      - name: GitHub Pages deploy action
        uses: rdarida/simple-github-pages-deploy-action@v1
        with:
          git-user: ioinitid
          git-email: ioinitid@gmail.com
          git-base-folder: ./dist
          commit-message: GitHub Pages deploy action
          branch: gh-pages
